# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c0a5beaa46373d4175ac122e63a027b52267df59a5c0ee0ab03ed047dda47a7c3d2cadf2f18eab55fb22babf4050ca0d5c845b9b79d3e26f0f024a1ee73759e

test:
  secret_key_base: 9e7e30b22cfc5a355af61b0b43039e249b819e3cfffe07d0de34dcc246dc6de79a8fea6f6978fd9cb207b58d1d242ff5ff435b6e4d2f945975118e4969973788

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
